name: Android CI

on:
  push:
    branches: [ "nightly" ]
    paths-ignore:
      - "**.md"
  pull_request:
    branches: [ "nightly" ]
    paths-ignore:
      - "**.md"

jobs:
  build:
    name: Build StarLight apk
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle
        
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4
      with:
        gradle-version: 8.7
        
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build debug
      run: ./gradlew assembleDebug

    - name: Extract artifact name
      run: |
        name="$(find app/build/outputs/apk/debug/ -type f -name 'StarLight-*')"
        echo "ARTIFACT_NAME=${name##*/}" >> $GITHUB_ENV

    - name: Upload the Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.ARTIFACT_NAME }}
        path: |
          app/build/outputs/apk/debug/${{ env.ARTIFACT_NAME }}
